### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by zhuting233** [SDchao/AutoVsCEnv_WPF#1]
未能找到路径“D:\code\.vscode\launch.json”的一部分。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   在 System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   在 System.IO.File.ReadAllText(String path)
   在 AutoVsCEnv_WPF.Operators.Installer.StartInstall()
   在 AutoVsCEnv_WPF.Forms.Installing.StartInstall(Object sender, DoWorkEventArgs args)

**Comment by SDchao** [comment]
明天会检查修改
如果急用可以手动进项目目录，把launch.json中的%%CPath%%修改为mingw目录

**Comment by SDchao** [comment]
我选择了项目文件夹为D:\code，无法复现此问题

**Comment by zhuting233** [comment]
> 我选择了项目文件夹为D:\code，无法复现此问题
下载了最新版，可是我电脑上还是不行，选好路径，一运行就报错

未能找到路径“D:\code\.vscode\launch.json”的一部分。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   在 System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   在 System.IO.File.ReadAllText(String path)
   在 AutoVsCEnv_WPF.Operators.Installer.StartInstall()
   在 AutoVsCEnv_WPF.Forms.Installing.StartInstall(Object sender, DoWorkEventArgs args)

**Comment by SDchao** [comment]
请问出现此问题时界面上的步骤文字是什么

**Comment by zhuting233** [comment]
> 请问出现此问题时界面上的步骤文字是什么

正在配置工作区

**Comment by SDchao** [comment]
仍然无法复现，建议检查一下可写入权限
或者换一个路径试试

**Comment by zhuting233** [comment]
emmm...用管理员权限运行的..  换了路径也是一样的问题
(╯▽╰)  那就这样吧   谢啦

**Comment by SDchao** [comment]
我尝试在全新虚拟机上运行

**Comment by SDchao** [comment]
已经发现问题，我在打包时忘记附上7z.dll

**Comment by SDchao** [comment]
新版本已发布，感谢协助！
