### ISSUE TITLE
Program路径出错

### ISSUE THREAD

**Issue by YUXIUV** [SDchao/AutoVsCEnv_WPF#10]
![image](https://user-images.githubusercontent.com/52365241/75439928-ab782b80-5995-11ea-8a07-062c6d121476.png)
非常非常感谢你提供了这个方便的软件，但是我遇见了一点问题，我用hello VScode运行时提示了我的exe路径出错。终端显示“终端将被任务重用，按任意键关闭。”并没能输出这句话。如果我到文件夹运行exe倒是可以。VScode版本是1.42.1.0

**Comment by SDchao** [comment]
你好！这种情况说明你可能安装了一个64为的MinGW，导致格式不被识别。
可以参考这个链接：https://stackoverflow.com/questions/47639685/gdb-error-not-in-executable-format-file-format-not-recognized

这个问题将会在下个版本修复

**Comment by SDchao** [comment]
这里需要您的协助：
能不能修改项目文件夹下.vscode/task.json中，
```json
"args": ["-g", "'${file}'", "-o", "'${fileDirname}/${fileBasenameNoExtension}.exe'"],
```

改为

```json
"args": ["-m32","-g", "'${file}'", "-o", "'${fileDirname}/${fileBasenameNoExtension}.exe'"],
```

看看问题会不会被修复

**Comment by YUXIUV** [comment]
非常感谢，解决了！

**Comment by SDchao** [comment]
好的，下个版本将统一修复该问题，感谢！

**Comment by EkSulfur** [comment]
新版本遇到了同样的问题，求助
