### ISSUE TITLE
未能解析此远程名称: 'sdchao.lanzous.com'    在 System.Net.HttpWebRequest.GetResponse()    在 AutoVsCEnv_WPF.Operators.LanzouLinkResolutor.ReadHttpSourceCode(String url) 位置 D:\Projects\WPF\AutoVsCEnv_WPF\AutoVsCEnv_WPF\Operators\LanzouLinkResolutor.cs:行号 150    在 AutoVsCEnv_WPF.Operators.LanzouLinkResolutor.Resolve(String LanzouLink) 位置 D:\Projects\WPF\AutoVsCEnv_WPF\AutoVsCEnv_WPF\Operators\LanzouLinkResolutor.cs:行号 20    在 AutoVsCEnv_WPF.Operators.Installer.StartInstall() 位置 D:\Projects\WPF\AutoVsCEnv_WPF\AutoVsCEnv_WPF\Operators\Installer.cs:行号 61    在 AutoVsCEnv_WPF.Forms.Installing.StartInstall(Object sender, DoWorkEventArgs args) 位置 D:\Projects\WPF\AutoVsCEnv_WPF\AutoVsCEnv_WPF\Forms\Installing.xaml.cs:行号 47[Feature] 新功能建议

### ISSUE THREAD

**Issue by XINGDIANZHU** [SDchao/AutoVsCEnv_WPF#107]
# 预期的功能

# 实现思路 [可选]

**Comment by shutdown-awa** [comment]
我也遇到了，改一下分享链接吧QAQ，不知道什么原因，就是经常访问不了lanzous.com这个域名，浏览器打开就说：lanzous.com已关闭连接QAQ

现在蓝奏云好像搞了一个lanzoui.com的域名，可以换一下awa

**Comment by JiaLian-Jiang** [comment]
> 我也遇到了，改一下分享链接吧QAQ，不知道什么原因，就是经常访问不了lanzous.com这个域名，浏览器打开就说：lanzous.com已关闭连接QAQ
> 
> 现在蓝奏云好像搞了一个lanzoui.c​​om的域名，可以换一下awa

hxd,应该在哪儿改域名呢

**Comment by shutdown-awa** [comment]
> > 我也遇到了，改一下分享链接吧QAQ，不知道什么原因，就是经常访问不了lanzous.com这个域名，浏览器打开就说：lanzous.com已关闭连接QAQ
> > 现在蓝奏云好像搞了一个lanzoui.c​​om的域名，可以换一下awa
> 
> hxd,应该在哪儿改域名呢

这个要开发者改awa，不然搜教程怎么让lanzous解析到lanzoui咯awa

**Comment by JiaLian-Jiang** [comment]
> > > 我也遇到了，改一下分享链接吧QAQ，不知道什么原因，就是经常访问不了lanzous.com这个域名，浏览器打开就说：lanzous.com已关闭连接QAQ
> > > 现在蓝奏云好像搞了一个lanzoui.c​​om的域名，可以换一下awa
> > 
> > 
> > hxd,应该在哪儿改域名呢
> 
> 这个要开发者改awa，不然搜教程怎么让lanzous解析到lanzoui咯awa

Thanks！我试试去

**Comment by shutdown-awa** [comment]
> > > > 我也遇到了，改一下分享链接吧QAQ，不知道什么原因，就是经常访问不了lanzous.com这个域名，浏览器打开就说：lanzous.com已关闭连接QAQ
> > > > 现在蓝奏云好像搞了一个lanzoui.c​​om的域名，可以换一下awa
> > > 
> > > 
> > > hxd,应该在哪儿改域名呢
> > 
> > 
> > 这个要开发者改awa，不然搜教程怎么让lanzous解析到lanzoui咯awa
> 
> Thanks！我试试去

找到解决方案dd！秋梨膏QAQ

**Comment by SDchao** [comment]
新版本已发布
