### ISSUE TITLE
出现问题啦

### ISSUE THREAD

**Issue by byoneh** [SDchao/AutoVsCEnv_WPF#111]
## 未能解析此远程名称: 'sdchao.lanzous.com'
   在 System.Net.HttpWebRequest.GetResponse()
   在 AutoVsCEnv_WPF.Operators.LanzouLinkResolutor.ReadHttpSourceCode(String url) 位置 D:\Projects\WPF\AutoVsCEnv_WPF\AutoVsCEnv_WPF\Operators\LanzouLinkResolutor.cs:行号 150
   在 AutoVsCEnv_WPF.Operators.LanzouLinkResolutor.Resolve(String LanzouLink) 位置 D:\Projects\WPF\AutoVsCEnv_WPF\AutoVsCEnv_WPF\Operators\LanzouLinkResolutor.cs:行号 20
   在 AutoVsCEnv_WPF.Operators.Installer.StartInstall() 位置 D:\Projects\WPF\AutoVsCEnv_WPF\AutoVsCEnv_WPF\Operators\Installer.cs:行号 61
   在 AutoVsCEnv_WPF.Forms.Installing.StartInstall(Object sender, DoWorkEventArgs args) 位置 D:\Projects\WPF\AutoVsCEnv_WPF\AutoVsCEnv_WPF\Forms\Installing.xaml.cs:行号 47

### 解压日志 Extract.log
【请用文本编辑器打开log文件并将内容粘贴到此处】

**Comment by byoneh** [comment]
07:32:28[INFO] Start install
07:32:28[INFO] GccPath: E:\vscodeCpp
07:32:28[INFO] projectPath: E:\vscodeCpp\practice
07:32:29[INFO] Found Gcc: True
07:32:31[INFO] Found code: 
07:40:59[INFO] Start install
07:40:59[INFO] GccPath: E:\vscodeCpp\vscode\cpppractise
07:40:59[INFO] projectPath: E:\vscodeCpp\vscode\cpppractise
07:41:01[INFO] Found Gcc: True

**Comment by SDchao** [comment]
新版本已发布
