### ISSUE TITLE
安装过程出现错误..

### ISSUE THREAD

**Issue by Yangzi73** [SDchao/AutoVsCEnv_WPF#12]
未能找到路径“E:\VsCodeCcode\.vscode\launch.json”的一部分。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   在 System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   在 System.IO.File.ReadAllText(String path)
   在 AutoVsCEnv_WPF.Operators.Installer.StartInstall() 位置 D:\Projects\WPF\AutoVsCEnv_WPF\AutoVsCEnv_WPF\Operators\Installer.cs:行号 85
   在 AutoVsCEnv_WPF.Forms.Installing.StartInstall(Object sender, DoWorkEventArgs args) 位置 D:\Projects\WPF\AutoVsCEnv_WPF\AutoVsCEnv_WPF\Forms\Installing.xaml.cs:行号 60

**Comment by SDchao** [comment]
麻烦附上运行目录下的两个log文件

**Comment by meustozil** [comment]
OK




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"SDchao"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月6日(星期五) 上午10:30
收件人:&nbsp;"SDchao/AutoVsCEnv_WPF"<AutoVsCEnv_WPF@noreply.github.com&gt;;
抄送:&nbsp;"迷"<1142190666@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [SDchao/AutoVsCEnv_WPF] 安装过程出现错误.. (#12)




麻烦附上运行目录下的两个log文件
