### ISSUE TITLE
有关容器的调试

### ISSUE THREAD

**Issue by wang-zh** [SDchao/AutoVsCEnv_WPF#123]
![image](https://user-images.githubusercontent.com/39694902/126426871-61c63673-08c2-458c-bc68-303092b281d5.png)
在调试的时候stl的容器不会显示内容希望能改进一下，或者说怎么配置呢？

**Comment by SDchao** [comment]
您好！这部分属于VScode的C/C++插件支持，与我的软件无关。

麻烦向此处反馈：https://github.com/microsoft/vscode-cpptools

**Comment by wang-zh** [comment]
经过查询与minGW的版本有关系
在使用i686-posix-dwarf-rev0，就可以了
![image](https://user-images.githubusercontent.com/39694902/126439199-e26c5286-b2e2-423e-9f91-f716ea1f17a3.png)
