### ISSUE TITLE
[BUG] 第一次配置路径输错了，第二次配置时出现的bug

### ISSUE THREAD

**Issue by yangmenghao666** [SDchao/AutoVsCEnv_WPF#134]
## 注意事项
请核对以下信息：
* 我已确认近期没有相似的Issue被提交（请使用issue搜索功能）
* 我已确认标题为问题概括而非**无意义内容**

## 这是我在运行期间遇到的错误弹窗内容
尝试执行未经授权的操作。
   在 Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   在 Microsoft.Win32.RegistryKey.SetValue(String name, Object value, RegistryValueKind valueKind)
   在 Microsoft.Win32.RegistryKey.SetValue(String name, Object value)
   在 System.Environment.SetEnvironmentVariable(String variable, String value, EnvironmentVariableTarget target)
   在 AutoVsCEnv_WPF.Operators.PathAdder.AddInUserPath(String newPath) 位置 D:\Projects\WPF\AutoVsCEnv_WPF\AutoVsCEnv_WPF\Operators\PathAdder.cs:行号 19
   在 AutoVsCEnv_WPF.Operators.Installer.StartInstall() 位置 D:\Projects\WPF\AutoVsCEnv_WPF\AutoVsCEnv_WPF\Operators\Installer.cs:行号 74
   在 AutoVsCEnv_WPF.Forms.Installing.StartInstall(Object sender, DoWorkEventArgs args) 位置 D:\Projects\WPF\AutoVsCEnv_WPF\AutoVsCEnv_WPF\Forms\Installing.xaml.cs:行号 47

### 杂项日志 debug.log
【请用文本编辑器打开log文件并将内容粘贴到此处】

### 解压日志 Extract.log
【请用文本编辑器打开log文件并将内容粘贴到此处】

**Comment by SDchao** [comment]
用管理员权限运行，请勿重复提交
