### ISSUE TITLE
配置不上

### ISSUE THREAD

**Issue by anlen123** [SDchao/AutoVsCEnv_WPF#2]
未能找到路径“F:\c\.vscode\launch.json”的一部分。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   在 System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   在 System.IO.File.ReadAllText(String path)
   在 AutoVsCEnv_WPF.Operators.Installer.StartInstall()
   在 AutoVsCEnv_WPF.Forms.Installing.StartInstall(Object sender, DoWorkEventArgs args)

**Comment by SDchao** [comment]
已经在排查了
因为本机不能复现，现在在找办法

**Comment by anlen123** [comment]
老版的虽然，大小大了点，环境包都封装了，但是可以离线使用啊，新版的需要联网，




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"SDchao"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月29日(星期三) 晚上7:37
收件人:&nbsp;"SDchao/AutoVsCEnv_WPF"<AutoVsCEnv_WPF@noreply.github.com&gt;;
抄送:&nbsp;"1761512493"<1761512493@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [SDchao/AutoVsCEnv_WPF] 配置不上 (#2)




已经在排查了
 因为本机不能复现，现在在找办法

**Comment by SDchao** [comment]
因为Github上传太慢，每次都需要额外蓝奏云确实有些麻烦
如果软件下载过MinGW的话不会重复下载

**Comment by SDchao** [comment]
已经发现问题，我在打包时忘记附上7z.dll

**Comment by SDchao** [comment]
新版本已发布，感谢协助！
