### ISSUE TITLE
救救孩子吧=.=

### ISSUE THREAD

**Issue by Xin-man** [SDchao/AutoVsCEnv_WPF#21]
无法获取Sign数据
   在 AutoVsCEnv_WPF.Operators.LanzouLinkResolutor.SolveDownloadUrl(String downloadPageUrl) 位置 D:\Projects\WPF\AutoVsCEnv_WPF\AutoVsCEnv_WPF\Operators\LanzouLinkResolutor.cs:行号 54
   在 AutoVsCEnv_WPF.Operators.LanzouLinkResolutor.Resolve(String LanzouLink) 位置 D:\Projects\WPF\AutoVsCEnv_WPF\AutoVsCEnv_WPF\Operators\LanzouLinkResolutor.cs:行号 20
   在 AutoVsCEnv_WPF.Operators.Installer.StartInstall() 位置 D:\Projects\WPF\AutoVsCEnv_WPF\AutoVsCEnv_WPF\Operators\Installer.cs:行号 61
   在 AutoVsCEnv_WPF.Forms.Installing.StartInstall(Object sender, DoWorkEventArgs args) 位置 D:\Projects\WPF\AutoVsCEnv_WPF\AutoVsCEnv_WPF\Forms\Installing.xaml.cs:行号 47

**Comment by Xin-man** [comment]
我电脑上也没d盘啊=.=只有C,E,F

**Comment by SDchao** [comment]
新版本已发布，感谢协助
