### ISSUE TITLE
1

### ISSUE THREAD

**Issue by easy-to-remeber** [SDchao/AutoVsCEnv_WPF#24]
未能解析此远程名称: 'www.lanzous.com'
   在 System.Net.HttpWebRequest.GetResponse()
   在 AutoVsCEnv_WPF.Operators.LanzouLinkResolutor.ReadHttpSourceCode(String url) 位置 D:\Projects\WPF\AutoVsCEnv_WPF\AutoVsCEnv_WPF\Operators\LanzouLinkResolutor.cs:行号 138
   在 AutoVsCEnv_WPF.Operators.LanzouLinkResolutor.SolveDownloadUrl(String downloadPageUrl) 位置 D:\Projects\WPF\AutoVsCEnv_WPF\AutoVsCEnv_WPF\Operators\LanzouLinkResolutor.cs:行号 29
   在 AutoVsCEnv_WPF.Operators.LanzouLinkResolutor.Resolve(String LanzouLink) 位置 D:\Projects\WPF\AutoVsCEnv_WPF\AutoVsCEnv_WPF\Operators\LanzouLinkResolutor.cs:行号 20
   在 AutoVsCEnv_WPF.Operators.Installer.StartInstall() 位置 D:\Projects\WPF\AutoVsCEnv_WPF\AutoVsCEnv_WPF\Operators\Installer.cs:行号 61
   在 AutoVsCEnv_WPF.Forms.Installing.StartInstall(Object sender, DoWorkEventArgs args) 位置 D:\Projects\WPF\AutoVsCEnv_WPF\AutoVsCEnv_WPF\Forms\Installing.xaml.cs:行号 47

**Comment by easy-to-remeber** [comment]
11:28:08[INFO] Start install
11:28:08[INFO] GccPath: D:\code\C Language
11:28:08[INFO] projectPath: D:\code\C Language
11:28:08[INFO] Found Gcc: True
11:28:08[INFO] Found code: NOTFOUND
11:28:11[WARN] Cannot Find code!
11:38:26[INFO] Start install
11:38:26[INFO] GccPath: D:\code\C Language
11:38:26[INFO] projectPath: D:\code\C Language\code
11:38:26[INFO] Found Gcc: False
11:38:26[INFO] Found code: NOTFOUND
11:38:31[WARN] Cannot Find code!
11:40:30[INFO] Start install
11:40:30[INFO] GccPath: D:\code\C Language
11:40:30[INFO] projectPath: D:\code\C Language\code
11:40:30[INFO] Found Gcc: False
11:40:31[INFO] Found code: NOTFOUND
11:40:32[WARN] Cannot Find code!
11:45:54[INFO] Start install
11:45:54[INFO] GccPath: D:\code\C Language
11:45:54[INFO] projectPath: D:\code\C Language\code
11:45:54[INFO] Found Gcc: False
11:45:54[INFO] Found code: NOTFOUND
11:45:55[WARN] Cannot Find code!
12:01:06[INFO] Start install
12:01:06[INFO] GccPath: D:\code\CLanguage
12:01:06[INFO] projectPath: D:\code\CLanguage\code
12:01:06[INFO] Found Gcc: False
12:01:06[INFO] Found code: NOTFOUND
12:01:08[WARN] Cannot Find code!
12:03:09[INFO] Start install
12:03:09[INFO] GccPath: D:\code\CLanguage\code
12:03:09[INFO] projectPath: D:\code\CLanguage\code
12:03:09[INFO] Found Gcc: False
12:03:10[INFO] Found code: NOTFOUND
12:03:10[WARN] Cannot Find code!

**Comment by SDchao** [comment]
请更换DNS，推荐使用114.114.114.114

**Comment by easy-to-remeber** [comment]
谢谢
