### ISSUE TITLE
玩坏了

### ISSUE THREAD

**Issue by Aari7** [SDchao/AutoVsCEnv_WPF#25]
无法获取Sign数据
   在 AutoVsCEnv_WPF.Operators.LanzouLinkResolutor.SolveDownloadUrl(String downloadPageUrl) 位置 D:\Projects\WPF\AutoVsCEnv_WPF\AutoVsCEnv_WPF\Operators\LanzouLinkResolutor.cs:行号 66
   在 AutoVsCEnv_WPF.Operators.LanzouLinkResolutor.Resolve(String LanzouLink) 位置 D:\Projects\WPF\AutoVsCEnv_WPF\AutoVsCEnv_WPF\Operators\LanzouLinkResolutor.cs:行号 20
   在 AutoVsCEnv_WPF.Operators.Installer.StartInstall() 位置 D:\Projects\WPF\AutoVsCEnv_WPF\AutoVsCEnv_WPF\Operators\Installer.cs:行号 61
   在 AutoVsCEnv_WPF.Forms.Installing.StartInstall(Object sender, DoWorkEventArgs args) 位置 D:\Projects\WPF\AutoVsCEnv_WPF\AutoVsCEnv_WPF\Forms\Installing.xaml.cs:行号 47

**Comment by SDchao** [comment]
这里重试了一下是可以的。
试试看重新下载一次？

**Comment by Aari7** [comment]
我已经手动配置好了，不过还是很感谢！
你的这个一键配置对新手来说真的是神器，太厉害了！加油！

**Comment by SDchao** [comment]
感谢支持
