### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by skyrookies** [SDchao/AutoVsCEnv_WPF#26]
无法获取Sign数据
   在 AutoVsCEnv_WPF.Operators.LanzouLinkResolutor.SolveDownloadUrl(String downloadPageUrl) 位置 D:\Projects\WPF\AutoVsCEnv_WPF\AutoVsCEnv_WPF\Operators\LanzouLinkResolutor.cs:行号 66
   在 AutoVsCEnv_WPF.Operators.LanzouLinkResolutor.Resolve(String LanzouLink) 位置 D:\Projects\WPF\AutoVsCEnv_WPF\AutoVsCEnv_WPF\Operators\LanzouLinkResolutor.cs:行号 20
   在 AutoVsCEnv_WPF.Operators.Installer.StartInstall() 位置 D:\Projects\WPF\AutoVsCEnv_WPF\AutoVsCEnv_WPF\Operators\Installer.cs:行号 61
   在 AutoVsCEnv_WPF.Forms.Installing.StartInstall(Object sender, DoWorkEventArgs args) 位置 D:\Projects\WPF\AutoVsCEnv_WPF\AutoVsCEnv_WPF\Forms\Installing.xaml.cs:行号 47

**Comment by SDchao** [comment]
这里重试了一下是可以的。
重新下载一次试试？

**Comment by SDchao** [comment]
请尝试使用新版
