### ISSUE TITLE
Issue  可能是没用代理？

### ISSUE THREAD

**Issue by Jackwcc** [SDchao/AutoVsCEnv_WPF#3]
尝试执行未经授权的操作。
   在 Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   在 Microsoft.Win32.RegistryKey.SetValue(String name, Object value, RegistryValueKind valueKind)
   在 Microsoft.Win32.RegistryKey.SetValue(String name, Object value)
   在 System.Environment.SetEnvironmentVariable(String variable, String value, EnvironmentVariableTarget target)
   在 AutoVsCEnv_WPF.Operators.PathAdder.AddInUserPath(String newPath)
   在 AutoVsCEnv_WPF.Operators.Installer.StartInstall()
   在 AutoVsCEnv_WPF.Forms.Installing.StartInstall(Object sender, DoWorkEventArgs args)

**Comment by SDchao** [comment]
不是哦，没有权限写入环境变量……
试试看用管理员权限执行

**Comment by Jackwcc** [comment]
![include](https://user-images.githubusercontent.com/31174272/74211766-50271780-4ccc-11ea-94f3-8a11e71c4e58.jpg)
![path](https://user-images.githubusercontent.com/31174272/74211777-57e6bc00-4ccc-11ea-950e-1ad51bf9e64a.png)
![编译器安装](https://user-images.githubusercontent.com/31174272/74211779-5ae1ac80-4ccc-11ea-8705-2d56928c7123.png)
![路径](https://user-images.githubusercontent.com/31174272/74211781-5c12d980-4ccc-11ea-8265-627f59947a6b.png)
![无法编译？](https://user-images.githubusercontent.com/31174272/74211788-62a15100-4ccc-11ea-9fd0-a391f0577f25.jpg)

**Comment by Jackwcc** [comment]
也重启了。。。不知道还有什么问题。。

**Comment by SDchao** [comment]
这个情况说明文件夹可能没有权限写出编译后的exe文件，和配置工具本身无关。
检查一下这个文件夹的读写权限

**Comment by Jackwcc** [comment]
谢谢，这个已经解决了，解决方法：
和up主B站里的方法一样，在D盘建了个工程文件夹，而没有在原来安装VSCode的目录下建工程文件夹了。 解压后就生成test.exe文件了。


但是又有新的问题了，
![error](https://user-images.githubusercontent.com/31174272/74216037-17903980-4cde-11ea-960e-c4d8796ecec7.png)

这个错误在B站的评论里也看到了，但没看到解决方法。按照README里的重新安装和配置的操作，也试了，无果。
感谢~

**Comment by Jackwcc** [comment]
解决了，参考b站一留言：
“调试显示preLaunchTask"g＋＋"已终止退出代码为1，把launch.json里的prelaunchtask g++用双斜杠注释掉可解决”

**Comment by SDchao** [comment]
实质上你只是禁用了编译任务，保持这项配置会导致之后新文件不会别编译为EXE
本质上并没有解决问题。
