### ISSUE TITLE
[BUG] 默认标题

### ISSUE THREAD

**Issue by thefish12** [SDchao/AutoVsCEnv_WPF#31]
这个"args": ["-g", "${file}", "-o", "${fileDirname}/${fileBasenameNoExtension}.exe"],中的"${file}"如果是按照原来的"**'**${file}**'**"就无法编译，而且"${fileDirname}/${fileBasenameNoExtension}.exe"如果是按照原来的"**'**${fileDirname}/${fileBasenameNoExtension}.exe **'** "也无法正常编译。

**Comment by thefish12** [comment]
在tasks.json的第13行

**Comment by SDchao** [comment]
我不太能明白你想反馈的问题
请给出出现的错误提示或信息
