### ISSUE TITLE
[BUG] 未能找到路径“E:\C\test.vscode\launch.json”的一部分。

### ISSUE THREAD

**Issue by alilcu** [SDchao/AutoVsCEnv_WPF#32]
未能找到路径“E:\C\test\.vscode\launch.json”的一部分。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   在 System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   在 System.IO.File.ReadAllText(String path)
   在 AutoVsCEnv_WPF.Operators.Installer.StartInstall() 位置 D:\Projects\WPF\AutoVsCEnv_WPF\AutoVsCEnv_WPF\Operators\Installer.cs:行号 83
   在 AutoVsCEnv_WPF.Forms.Installing.StartInstall(Object sender, DoWorkEventArgs args) 位置 D:\Projects\WPF\AutoVsCEnv_WPF\AutoVsCEnv_WPF\Forms\Installing.xaml.cs:行号 47

**Comment by SDchao** [comment]
麻烦附上extract.log 与 debug.log
