### ISSUE TITLE
[BUG] 默认标题

### ISSUE THREAD

**Issue by baici1** [SDchao/AutoVsCEnv_WPF#34]
无法连接到远程服务器
   在 System.Net.HttpWebRequest.GetResponse()
   在 AutoVsCEnv_WPF.Operators.LanzouLinkResolutor.ReadHttpSourceCode(String url) 位置 D:\Projects\WPF\AutoVsCEnv_WPF\AutoVsCEnv_WPF\Operators\LanzouLinkResolutor.cs:行号 134
   在 AutoVsCEnv_WPF.Operators.LanzouLinkResolutor.Resolve(String LanzouLink) 位置 D:\Projects\WPF\AutoVsCEnv_WPF\AutoVsCEnv_WPF\Operators\LanzouLinkResolutor.cs:行号 20
   在 AutoVsCEnv_WPF.Operators.Installer.StartInstall() 位置 D:\Projects\WPF\AutoVsCEnv_WPF\AutoVsCEnv_WPF\Operators\Installer.cs:行号 61
   在 AutoVsCEnv_WPF.Forms.Installing.StartInstall(Object sender, DoWorkEventArgs args) 位置 D:\Projects\WPF\AutoVsCEnv_WPF\AutoVsCEnv_WPF\Forms\Installing.xaml.cs:行号 47

**Comment by SDchao** [comment]
建议检查网络或者重试。
先看看浏览器能否访问这个链接: https://sdchao.lanzous.com/i7iwn2h

**Comment by SDchao** [comment]
#36
