### ISSUE TITLE
VSCode 配置失败

### ISSUE THREAD

**Issue by 757356** [SDchao/AutoVsCEnv_WPF#35]
如图
![MFSLAISDR(ZPM6`F%E)EDPT](https://user-images.githubusercontent.com/61815273/83419282-6f061100-a457-11ea-8ae0-88347b87eb93.png)

**Comment by SDchao** [comment]
检查一下C/C++插件有没有正确安装

**Comment by 757356** [comment]
怎么检查啊？（不会检查，百度也没有找到方法）
这是安装MInGW的文件夹
![CRPH%Q`%0(U2 HA~FJRSSAG](https://user-images.githubusercontent.com/61815273/83478826-749c3f00-a4c9-11ea-9ef1-2177de3424a0.png)
![GU8$JGX9(I%47B)(B%ZL_SV](https://user-images.githubusercontent.com/61815273/83478830-75cd6c00-a4c9-11ea-8d78-facf48234fe0.png)
这是按open launch.json 后的结果
![NV5`0TDIQ Y`IL$P2U0X70V](https://user-images.githubusercontent.com/61815273/83478833-77972f80-a4c9-11ea-8e5d-6e1e93a1a9c6.png)

**Comment by 757356** [comment]
怎么检查啊？（百度也没有找到该怎么检查）
这是mingw安装的文件夹和按open launch.json后的结果的图片
![CRPH%Q`%0(U2 HA~FJRSSAG](https://user-images.githubusercontent.com/61815273/83479078-25a2d980-a4ca-11ea-9c3a-d9044c9b2995.png)
![GU8$JGX9(I%47B)(B%ZL_SV](https://user-images.githubusercontent.com/61815273/83479084-2a678d80-a4ca-11ea-8746-aa761e746719.png)
![NV5`0TDIQ Y`IL$P2U0X70V](https://user-images.githubusercontent.com/61815273/83479088-2c315100-a4ca-11ea-822e-00ac25b44ad8.png)

**Comment by 757356** [comment]
![CRPH%Q`%0(U2 HA~FJRSSAG](https://user-images.githubusercontent.com/61815273/83479171-67338480-a4ca-11ea-89c9-b16fd697644f.png)

**Comment by 757356** [comment]
![GU8$JGX9(I%47B)(B%ZL_SV](https://user-images.githubusercontent.com/61815273/83479184-70245600-a4ca-11ea-84b5-bfe67faaabe6.png)
好像不能一次上传太多图片。。

**Comment by SDchao** [comment]
在VScode的插件列表中检查一下有没有C/C++，如果没有手动安装一下

**Comment by 757356** [comment]
这里吗？它显示安装了啊
![RM8{HW3R(19 DAL {}RZ0OF](https://user-images.githubusercontent.com/61815273/83503248-5cdab000-a4f5-11ea-95af-f316bd3413f4.png)

**Comment by SDchao** [comment]
试试看重装插件吧……
cppdbg的debug类型是这个插件提供的

**Comment by 757356** [comment]
好的，现在它可以了。谢谢你了！
你会用它配置Python吗？我百度找到的教程我看不懂。。

**Comment by SDchao** [comment]
Python配置不在解答范围内……
你先装python，再装vscode插件，就可以了

**Comment by 757356** [comment]
都装了，还是不可以。。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Owen Chen"<notifications@github.com&gt;; 
发送时间: 2020年6月4日(星期四) 下午5:38
收件人: "SDchao/AutoVsCEnv_WPF"<AutoVsCEnv_WPF@noreply.github.com&gt;; 
抄送: "梦"<757356249@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [SDchao/AutoVsCEnv_WPF] VSCode 配置失败 (#35)





 
Python配置不在解答范围内……
 你先装python，再装vscode插件，就可以了
