### ISSUE TITLE
[BUG] 似乎是因为 ‘\'  '/’ 出现的问题

### ISSUE THREAD

**Issue by Sword-keeper** [SDchao/AutoVsCEnv_WPF#38]
![image](https://user-images.githubusercontent.com/43240918/83739184-d6a2a300-a687-11ea-8db5-7be4a58e4873.png)

**Comment by Sword-keeper** [comment]
我运行了 test.cpp 也是这个问题

**Comment by SDchao** [comment]
在我本机上两种斜杠混用没有问题
在你的机器上修改task.json，
把
```
"args": ["-m32","-g", "'${file}'", "-o", "'${fileDirname}/${fileBasenameNoExtension}.exe'"],
```
改为
```
"args": ["-m32","-g", "'${file}'", "-o", "'${fileDirname}\\${fileBasenameNoExtension}.exe'"],
```
后问题能否解决？

**Comment by Sword-keeper** [comment]
![image](https://user-images.githubusercontent.com/43240918/83742942-9d206680-a68c-11ea-943f-b30541ac0b4c.png)
额  。。 还是不行 不好意思 我搞错了 。  不是 斜杠的问题

**Comment by Sword-keeper** [comment]
额 。。 还是不行 不好意思 我搞错了 。 不是 斜杠的问题

g++: error: 'e:\CPackage\code\test.cpp': Invalid argument
g++: fatal error: no input files
compilation terminated.
The terminal process terminated with exit code: 1

**Comment by SDchao** [comment]
参考一下这个issue能否解决你的问题
https://github.com/SDchao/AutoVsCEnv_WPF/issues/4#issuecomment-637275327

**Comment by Sword-keeper** [comment]
还会弹出窗口说   Errors exists after running preLaunchTask 'g++'

**Comment by Sword-keeper** [comment]
嗷嗷  解决了  多谢作者  省了不少时间~

**Comment by SDchao** [comment]
新版本已发布，感谢协助！
