### ISSUE TITLE
[BUG] 已经管理员运行了，可是修改Path路径是报错

### ISSUE THREAD

**Issue by CoderChen01** [SDchao/AutoVsCEnv_WPF#39]
# 已经管理员运行了

## 注意事项
请核对以下信息：
* 我已确认近期没有相似的Issue被提交（请使用issue搜索功能）
* 我已确认标题为问题概括而非**无意义内容**

## 这是我在运行期间遇到的错误弹窗内容
尝试执行未经授权的操作。
   在 Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   在 Microsoft.Win32.RegistryKey.SetValue(String name, Object value, RegistryValueKind valueKind)
   在 Microsoft.Win32.RegistryKey.SetValue(String name, Object value)
   在 System.Environment.SetEnvironmentVariable(String variable, String value, EnvironmentVariableTarget target)
   在 AutoVsCEnv_WPF.Operators.PathAdder.AddInUserPath(String newPath) 位置 D:\Projects\WPF\AutoVsCEnv_WPF\AutoVsCEnv_WPF\Operators\PathAdder.cs:行号 19
   在 AutoVsCEnv_WPF.Operators.Installer.StartInstall() 位置 D:\Projects\WPF\AutoVsCEnv_WPF\AutoVsCEnv_WPF\Operators\Installer.cs:行号 75
   在 AutoVsCEnv_WPF.Forms.Installing.StartInstall(Object sender, DoWorkEventArgs args) 位置 D:\Projects\WPF\AutoVsCEnv_WPF\AutoVsCEnv_WPF\Forms\Installing.xaml.cs:行号 47

## 这是我当时正在进行的操作
正在修改Path路径
### debug.log
【请用文本编辑器打开log文件并将内容粘贴到此处】
02:04:40[INFO] Start install
02:04:40[INFO] GccPath: A:\Ccompiler
02:04:40[INFO] projectPath: B:\Projects\Ccode
02:04:41[INFO] Found Gcc: False
02:04:41[INFO] Found code: 
02:04:41[INFO] Created Download Link: https://vip.d0.baidupan.com/file/?AGZVawAxATBVXFZuBjNQPFNsAzsDEQVuVz5UFVVeV3gFMlV4CHNVZ1RrBz0ENQdZWmkGZ189ATJXZAcyVT9UYgAwVTAAagFzVWVWcwZvUGdTMAM+A2UFNFdmVGJVPFdwBXVVcghoVTNUMgdgBGkHKVoxBjJfLwExV2MHLlU5VDMAZFU3AGkBYlU3VmMGM1BpUzgDZANsBTZXNVQ0VT9XZgUxVWYIMVVnVDAHNARgB2JaMAYyXzkBYlc2BzNVJ1RiAHpVJAAoASZVZlZyBjtQNVM0AzUDbAU/V2ZUYVU7V3AFcVVrCDhVZFRkB2wEYQczWjkGMl8zATBXaAcxVTFUZwAuVSwAewEzVW9WdwZvUGBTPAM/A20FNFdjVGBVMVdlBTxVJAggVXFUdQdsBGEHM1o3BjdfNAE7V2gHOVU7VGUAJlV3ADQBJVU+VjMGZFB/UzwDMANyBTVXflRgVTE=
02:15:15[INFO] Start install
02:15:15[INFO] GccPath: A:\Ccompiler
02:15:15[INFO] projectPath: B:\Projects\Ccode
02:15:15[INFO] Found Gcc: False
02:15:15[INFO] Found code: 
02:18:15[INFO] Start install
02:18:15[INFO] GccPath: A:\Ccompiler
02:18:15[INFO] projectPath: B:\Projects\Ccode
02:18:15[INFO] Found Gcc: False
02:18:15[INFO] Found code: 

### Extract.log
【请用文本编辑器打开log文件并将内容粘贴到此处】
02:04:54[INFO] 
02:04:54[INFO] 7-Zip 19.00 (x86) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21
02:04:54[INFO] 
02:04:54[INFO] Scanning the drive for archives:
02:04:54[INFO] 1 file, 69893605 bytes (67 MiB)
02:04:54[INFO] 
02:04:54[INFO] Extracting archive: data\MinGW.7z
02:04:57[INFO] --
02:04:57[INFO] Path = data\MinGW.7z
02:04:57[INFO] Type = 7z
02:04:57[INFO] Physical Size = 69893605
02:04:57[INFO] Headers Size = 24575
02:04:57[INFO] Method = LZMA2:25
02:04:57[INFO] Solid = +
02:04:57[INFO] Blocks = 1
02:04:57[INFO] 
02:04:57[INFO] Everything is Ok
02:04:57[INFO] 
02:04:57[INFO] Folders: 91
02:04:57[INFO] Files: 1752
02:04:57[INFO] Size:       254628040
02:04:57[INFO] Compressed: 69893605
02:04:57[INFO] 
02:04:57[INFO] 
02:04:57[INFO] 
02:15:15[INFO] 
02:15:15[INFO] 7-Zip 19.00 (x86) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21
02:15:15[INFO] 
02:15:15[INFO] Scanning the drive for archives:
02:15:15[INFO] 1 file, 69893605 bytes (67 MiB)
02:15:15[INFO] 
02:15:15[INFO] Extracting archive: data\MinGW.7z
02:15:19[INFO] --
02:15:19[INFO] Path = data\MinGW.7z
02:15:19[INFO] Type = 7z
02:15:19[INFO] Physical Size = 69893605
02:15:19[INFO] Headers Size = 24575
02:15:19[INFO] Method = LZMA2:25
02:15:19[INFO] Solid = +
02:15:19[INFO] Blocks = 1
02:15:19[INFO] 
02:15:19[INFO] Everything is Ok
02:15:19[INFO] 
02:15:19[INFO] Folders: 91
02:15:19[INFO] Files: 1752
02:15:19[INFO] Size:       254628040
02:15:19[INFO] Compressed: 69893605
02:15:19[INFO] 
02:15:19[INFO] 
02:15:19[INFO] 
02:18:15[INFO] 
02:18:15[INFO] 7-Zip 19.00 (x86) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21
02:18:15[INFO] 
02:18:15[INFO] Scanning the drive for archives:
02:18:15[INFO] 1 file, 69893605 bytes (67 MiB)
02:18:15[INFO] 
02:18:15[INFO] Extracting archive: data\MinGW.7z
02:18:19[INFO] --
02:18:19[INFO] Path = data\MinGW.7z
02:18:19[INFO] Type = 7z
02:18:19[INFO] Physical Size = 69893605
02:18:19[INFO] Headers Size = 24575
02:18:19[INFO] Method = LZMA2:25
02:18:19[INFO] Solid = +
02:18:19[INFO] Blocks = 1
02:18:19[INFO] 
02:18:19[INFO] Everything is Ok
02:18:19[INFO] 
02:18:19[INFO] Folders: 91
02:18:19[INFO] Files: 1752
02:18:19[INFO] Size:       254628040
02:18:19[INFO] Compressed: 69893605
02:18:19[INFO] 
02:18:19[INFO]

**Comment by SDchao** [comment]
麻烦确认一下你当前的账户是否拥有系统管理员（Administrator)权限

**Comment by CoderChen01** [comment]
![image](https://user-images.githubusercontent.com/61137732/83850741-eed7f800-a743-11ea-8c52-6f50c8192434.png)
### 有的有的

**Comment by CoderChen01** [comment]
> 麻烦确认一下你当前的账户是否拥有系统管理员（Administrator)权限

![image](https://user-images.githubusercontent.com/61137732/83850821-0dd68a00-a744-11ea-89b1-78995b078ad6.png)

**Comment by SDchao** [comment]
你的运行方式是直接打开，还是右键以管理员身份运行？
你在运行时应该会出现UAC弹窗

**Comment by CoderChen01** [comment]
> 你的运行方式是直接打开，还是右键以管理员身份运行？
> 你在运行时应该会出现UAC弹窗

是这样的呢

**Comment by SDchao** [comment]
这样的话是.Net程序集的BUG了，我暂时没有办法修复，你可以试试看更换.Net版本

**Comment by CoderChen01** [comment]
> 这样的话是.Net程序集的BUG了，我暂时没有办法修复，你可以试试看更换.Net版本

好的，谢谢，我待会重启下试试。
