### ISSUE TITLE
[错误]

### ISSUE THREAD

**Issue by 02ww** [SDchao/AutoVsCEnv_WPF#45]
## 注意事项
请核对以下信息：
* 我已确认近期没有相似的Issue被提交（请使用issue搜索功能）
* 我已确认标题为问题概括而非**无意义内容**

## 这是我在运行期间遇到的错误弹窗内容
未能解析此远程名称: 'sdchao.lanzous.com'
   在 System.Net.HttpWebRequest.GetResponse()
   在 AutoVsCEnv_WPF.Operators.LanzouLinkResolutor.ReadHttpSourceCode(String url) 位置 D:\Projects\WPF\AutoVsCEnv_WPF\AutoVsCEnv_WPF\Operators\LanzouLinkResolutor.cs:行号 134
   在 AutoVsCEnv_WPF.Operators.LanzouLinkResolutor.Resolve(String LanzouLink) 位置 D:\Projects\WPF\AutoVsCEnv_WPF\AutoVsCEnv_WPF\Operators\LanzouLinkResolutor.cs:行号 20
   在 AutoVsCEnv_WPF.Operators.Installer.StartInstall() 位置 D:\Projects\WPF\AutoVsCEnv_WPF\AutoVsCEnv_WPF\Operators\Installer.cs:行号 61
   在 AutoVsCEnv_WPF.Forms.Installing.StartInstall(Object sender, DoWorkEventArgs args) 位置 D:\Projects\WPF\AutoVsCEnv_WPF\AutoVsCEnv_WPF\Forms\Installing.xaml.cs:行号 47

## 这是我当时正在进行的操作
运行AutoVsCEnv_WPF.exe
## 这是我软件目录下的log文件内容 (debug.log 和 Extract.log)
无文件
### debug.log
【请用文本编辑器打开log文件并将内容粘贴到此处】
无文件
### Extract.log
【请用文本编辑器打开log文件并将内容粘贴到此处】
无文件

**Comment by SDchao** [comment]
更换DNS为114.114.114.114
