### ISSUE TITLE
debug.log

### ISSUE THREAD

**Issue by Kyokyopp** [SDchao/AutoVsCEnv_WPF#5]
不能正确导入MinGW路径，需要手动修改
07:36:26[INFO] Start install
07:36:26[INFO] GccPath: F:\MinGW
07:36:26[INFO] projectPath: F:\gxchengxu22
07:36:26[INFO] Found Gcc: True
07:36:26[INFO] Found code: 
07:36:27[INFO] Created Download Link: https://vip.d0.baidupan.com/file/?BWNSbA4/BTQGDwE5BjMAbFFuDzcDEVE6Bm8AQVVeBikCNQYrCXIENgY5VG4GN1AOVGcHZl89ADMHNFFkBmxQZgU1UjcOZAV3BjYBJAZvADdRMg8yA2VRYAY3ADZVPAYhAnIGIQlpBGIGYFQzBmtQflQ/BzNfLwAwBzNReAZqUDcFYVIwDmcFZgZkATQGMwA5UToPaANsUWIGZABgVT8GNwI2BjUJMAQ2BmJUZwZiUDVUPgczXzkAYwdmUWUGdFBmBX9SIw4mBSIGNQElBjsAZVE2DzkDbFFrBjcANVU7BiECdgY4CTkENQY2VD8GY1BkVDYHM180ADAHMVFuBmJQZgUrUisOdQU3BjwBIAZvADBRPg8yA21RZwYwADBVMQY3AjYGdwkhBCAGJ1Q/BmNQZFQ5BzZfNAA6BzhRbwZoUGEFI1JwDjoFIQZtAWQGZAAvUTkPOANyUWQGNgAoVTgGMQI1
07:36:57[INFO] Launch File Path: F:\gxchengxu22\.vscode\launch.json
07:36:57[INFO] New File Content:
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "targetArchitecture": "x86",
            "program": "${fileDirname}/${fileBasenameNoExtension}.exe",
            "miDebuggerPath": "D:/mingw/bin/gdb.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${fileDirname}",
            "externalConsole": true,
            "preLaunchTask": "g++"
        }
    ]
}
07:36:57[INFO] Property File Path: F:\gxchengxu22\.vscode\c_cpp_properties.json
07:36:57[INFO] New File Content:
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**",
                "D:/mingw/include/*"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "compilerPath": "D:/mingw/bin/gcc.exe",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "gcc-x64"
        }
    ],
    "version": 4
}
09:45:31[INFO] Start install
09:45:31[INFO] GccPath: F:\minw64\mingw64
09:45:31[INFO] projectPath: F:\minw64\mingw64
09:45:31[INFO] Found Gcc: True
09:45:31[INFO] Found code: 
09:46:28[INFO] Start install
09:46:28[INFO] GccPath: F:\minw64\mingw64
09:46:28[INFO] projectPath: F:\gxchenxu3
09:46:28[INFO] Found Gcc: True
09:46:29[INFO] Found code: 
09:46:32[INFO] Launch File Path: F:\gxchenxu3\.vscode\launch.json
09:46:32[INFO] New File Content:
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "targetArchitecture": "x86",
            "program": "${fileDirname}/${fileBasenameNoExtension}.exe",
            "miDebuggerPath": "D:/mingw/bin/gdb.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${fileDirname}",
            "externalConsole": true,
            "preLaunchTask": "g++"
        }
    ]
}
09:46:32[INFO] Property File Path: F:\gxchenxu3\.vscode\c_cpp_properties.json
09:46:32[INFO] New File Content:
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**",
                "D:/mingw/include/*"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "compilerPath": "D:/mingw/bin/gcc.exe",
            "cStandard": "c11",
            "cppStandard": "c++17",
            "intelliSenseMode": "gcc-x64"
        }
    ],
    "version": 4
}

**Comment by SDchao** [comment]
……我最新版本打包有误，马上修改

**Comment by SDchao** [comment]
新版本已发布，感谢分享！
