### ISSUE TITLE
虽然可以在终端使用，但是无法调试的问题

### ISSUE THREAD

**Issue by wanwuxingzhang** [SDchao/AutoVsCEnv_WPF#6]
终端可以打开，但是vs里调试出现问题[配置的类型“cppdbg”不受支持]提示打开launch.json这是什么

**Comment by SDchao** [comment]
麻烦发一下launch.json文件，在项目文件夹内.vscode里面
同时请检查C/C++插件有没有安装

**Comment by wanwuxingzhang** [comment]
问题解决了。
文件应该没问题。
插件之前禁用了没有调整。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"SDchao"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月19日(星期三) 上午9:55
收件人:&nbsp;"SDchao/AutoVsCEnv_WPF"<AutoVsCEnv_WPF@noreply.github.com&gt;;
抄送:&nbsp;"飞翔的秃头子。"<2475602500@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [SDchao/AutoVsCEnv_WPF] 虽然可以在终端使用，但是无法调试的问题 (#6)




麻烦发一下launch.json文件，在项目文件夹内.vscode里面
 同时请检查C/C++插件有没有安装
