### ISSUE TITLE
基础连接已经关闭

### ISSUE THREAD

**Issue by WFWYYE** [SDchao/AutoVsCEnv_WPF#64]
## 注意事项
请核对以下信息：
* 我已确认近期没有相似的Issue被提交（请使用issue搜索功能）
* 我已确认标题为问题概括而非**无意义内容**

## 这是我在运行期间遇到的错误弹窗内容
基础连接已经关闭: 未能为 SSL/TLS 安全通道建立信任关系。
   在 System.Net.HttpWebRequest.GetResponse()
   在 AutoVsCEnv_WPF.Operators.LanzouLinkResolutor.ReadHttpSourceCode(String url) 位置 D:\Projects\WPF\AutoVsCEnv_WPF\AutoVsCEnv_WPF\Operators\LanzouLinkResolutor.cs:行号 134
   在 AutoVsCEnv_WPF.Operators.LanzouLinkResolutor.Resolve(String LanzouLink) 位置 D:\Projects\WPF\AutoVsCEnv_WPF\AutoVsCEnv_WPF\Operators\LanzouLinkResolutor.cs:行号 20
   在 AutoVsCEnv_WPF.Operators.Installer.StartInstall() 位置 D:\Projects\WPF\AutoVsCEnv_WPF\AutoVsCEnv_WPF\Operators\Installer.cs:行号 61
   在 AutoVsCEnv_WPF.Forms.Installing.StartInstall(Object sender, DoWorkEventArgs args) 位置 D:\Projects\WPF\AutoVsCEnv_WPF\AutoVsCEnv_WPF\Forms\Installing.xaml.cs:行号 47

### debug.log
【请用文本编辑器打开log文件并将内容粘贴到此处】

### Extract.log
【请用文本编辑器打开log文件并将内容粘贴到此处】

**Comment by SDchao** [comment]
检查一下系统时间，证书是否正常。
这个应该不是配置工具的问题
