### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by JYRcrazy** [SDchao/AutoVsCEnv_WPF#8]
未将对象引用设置到对象的实例。
   在 AutoVsCEnv_WPF.Operators.PathAdder.AddInUserPath(String newPath) 位置 D:\Projects\WPF\AutoVsCEnv_WPF\AutoVsCEnv_WPF\Operators\PathAdder.cs:行号 14
   在 AutoVsCEnv_WPF.Operators.Installer.StartInstall() 位置 D:\Projects\WPF\AutoVsCEnv_WPF\AutoVsCEnv_WPF\Operators\Installer.cs:行号 77
   在 AutoVsCEnv_WPF.Forms.Installing.StartInstall(Object sender, DoWorkEventArgs args) 位置 D:\Projects\WPF\AutoVsCEnv_WPF\AutoVsCEnv_WPF\Forms\Installing.xaml.cs:行号 60

**Comment by SDchao** [comment]
请问这个问题在重复运行时会出现吗

**Comment by JYRcrazy** [comment]
没试过第二次，我再试试

**Comment by JYRcrazy** [comment]
方便加个别的方式指导一下吗？

**Comment by JYRcrazy** [comment]
问题解决了，是我的问题，谢谢大佬
