### ISSUE TITLE
[BUG] 求解

### ISSUE THREAD

**Issue by c12h180** [SDchao/AutoVsCEnv_WPF#88]
无法转化data为Json:
{ 'action':'downprocess','signs':ajaxdata,'sign':'CW9SbAo7U2IACQY5VmZSblU_bBDUHawYyBDQEMlE_aUmRTdVZ1AGAOawNjB2BWMwU8WzVQbVA_aV2UCMQ_c_c','ves':1,'websign':'' }
'CW9SbAo7U2IACQY5VmZSblU_bBDUHawYyBDQEMlE_aUmRTdVZ1AGAOawNjB2BWMwU8WzVQbVA_aV2UCMQ_c_c': 
   在 AutoVsCEnv_WPF.Operators.LanzouLinkResolutor.SolveDownloadUrl(String downloadPageUrl) 位置 D:\Projects\WPF\AutoVsCEnv_WPF\AutoVsCEnv_WPF\Operators\LanzouLinkResolutor.cs:行号 83
   在 AutoVsCEnv_WPF.Operators.LanzouLinkResolutor.Resolve(String LanzouLink) 位置 D:\Projects\WPF\AutoVsCEnv_WPF\AutoVsCEnv_WPF\Operators\LanzouLinkResolutor.cs:行号 20
   在 AutoVsCEnv_WPF.Operators.Installer.StartInstall() 位置 D:\Projects\WPF\AutoVsCEnv_WPF\AutoVsCEnv_WPF\Operators\Installer.cs:行号 61
   在 AutoVsCEnv_WPF.Forms.Installing.StartInstall(Object sender, DoWorkEventArgs args) 位置 D:\Projects\WPF\AutoVsCEnv_WPF\AutoVsCEnv_WPF\Forms\Installing.xaml.cs:行号 47

### debug.log
【请用文本编辑器打开log文件并将内容粘贴到此处】

### Extract.log
【请用文本编辑器打开log文件并将内容粘贴到此处】

**Comment by SDchao** [comment]
新版本已发布，感谢协助
