### ISSUE TITLE
[BUG] 默认标题

### ISSUE THREAD

**Issue by hanmoliuxuan** [SDchao/AutoVsCEnv_WPF#89]
## 注意事项
请核对以下信息：
* 我已确认近期没有相似的Issue被提交（请使用issue搜索功能）
* 我已确认标题为问题概括而非**无意义内容**

## 这是我在运行期间遇到的错误弹窗内容
无法转化data为Json:
{ 'action':'downprocess','signs':ajaxdata,'sign':'AWcBPws6BTRWXwA_aV2dcYFoxAjNVOVdjCzsANlA_bVmABJwckXDwOa1MzUzRUMVNqUjAOM1A7CzgKPA_c_c','ves':1,'websign':'' }
'AWcBPws6BTRWXwA_aV2dcYFoxAjNVOVdjCzsANlA_bVmABJwckXDwOa1MzUzRUMVNqUjAOM1A7CzgKPA_c_c': 
   在 AutoVsCEnv_WPF.Operators.LanzouLinkResolutor.SolveDownloadUrl(String downloadPageUrl) 位置 D:\Projects\WPF\AutoVsCEnv_WPF\AutoVsCEnv_WPF\Operators\LanzouLinkResolutor.cs:行号 83
   在 AutoVsCEnv_WPF.Operators.LanzouLinkResolutor.Resolve(String LanzouLink) 位置 D:\Projects\WPF\AutoVsCEnv_WPF\AutoVsCEnv_WPF\Operators\LanzouLinkResolutor.cs:行号 20
   在 AutoVsCEnv_WPF.Operators.Installer.StartInstall() 位置 D:\Projects\WPF\AutoVsCEnv_WPF\AutoVsCEnv_WPF\Operators\Installer.cs:行号 61
   在 AutoVsCEnv_WPF.Forms.Installing.StartInstall(Object sender, DoWorkEventArgs args) 位置 D:\Projects\WPF\AutoVsCEnv_WPF\AutoVsCEnv_WPF\Forms\Installing.xaml.cs:行号 47

### debug.log
无法转化data为Json:
### Extract.log
【请用文本编辑器打开log文件并将内容粘贴到此处】

**Comment by SDchao** [comment]
新版本已发布，感谢协助
