### ISSUE TITLE
there are something wrong。。。。

### ISSUE THREAD

**Issue by run-197** [SDchao/AutoVsCEnv_WPF#9]
未能找到aria2c.exe
尝试查找的目录为libs\aria2c.exe
   在 AutoVsCEnv_WPF.Operators.DownloadHelper.Download(String url, String saveDirectory) 位置 D:\Projects\WPF\AutoVsCEnv_WPF\AutoVsCEnv_WPF\Operators\DownloadHelper.cs:行号 20
   在 AutoVsCEnv_WPF.Operators.Installer.StartInstall() 位置 D:\Projects\WPF\AutoVsCEnv_WPF\AutoVsCEnv_WPF\Operators\Installer.cs:行号 70
   在 AutoVsCEnv_WPF.Forms.Installing.StartInstall(Object sender, DoWorkEventArgs args) 位置 D:\Projects\WPF\AutoVsCEnv_WPF\AutoVsCEnv_WPF\Forms\Installing.xaml.cs:行号 60

**Comment by SDchao** [comment]
请先解压再运行，确保程序所在目录下有libs文件夹。
如果仍有问题，请重开Issue
