### ISSUE TITLE
.c文件运行闪退

### ISSUE THREAD

**Issue by Ethereal-bang** [SDchao/AutoVsCEnv_WPF#93]
调试文件成功运行，但是自己在当前文件夹里新建的 .c 文件可以报错但运行后闪退。
![image](https://user-images.githubusercontent.com/70147063/109453992-3fd80b00-7a8e-11eb-89ee-577eb62ebf64.png)
也就是这个运行程序闪退

**Comment by ysun0806** [comment]
自己代码加上个暂停就行了 
system(pause);
